<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "giesenwebentwicklung"
 *
 * Auto generated by Extension Builder 2018-09-12
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Templates Eigene Webseite',
    'description' => '',
    'category' => 'distribution',
    'author' => 'Martin Giesen',
    'author_email' => 'martin@giesen-webentwicklung.de',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-9.9.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
